/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// BulkIssuePropertyUpdateRequestFilter : The bulk operation filter.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkIssuePropertyUpdateRequestFilter {
    /// List of issues to perform the bulk operation on.
    #[serde(rename = "entityIds", skip_serializing_if = "Option::is_none")]
    pub entity_ids: Option<Vec<i64>>,
    /// The value of properties to perform the bulk operation on.
    #[serde(rename = "currentValue", skip_serializing_if = "Option::is_none")]
    pub current_value: Option<serde_json::Value>,
    /// Whether the bulk operation occurs only when the property is present on or absent from an issue.
    #[serde(rename = "hasProperty", skip_serializing_if = "Option::is_none")]
    pub has_property: Option<bool>,
}

impl BulkIssuePropertyUpdateRequestFilter {
    /// The bulk operation filter.
    pub fn new() -> BulkIssuePropertyUpdateRequestFilter {
        BulkIssuePropertyUpdateRequestFilter {
            entity_ids: None,
            current_value: None,
            has_property: None,
        }
    }
}
