/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// IssueUpdateDetailsHistoryMetadata : Additional issue history details.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IssueUpdateDetailsHistoryMetadata {
    /// The type of the history record.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// The description of the history record.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The description key of the history record.
    #[serde(rename = "descriptionKey", skip_serializing_if = "Option::is_none")]
    pub description_key: Option<String>,
    /// The activity described in the history record.
    #[serde(
        rename = "activityDescription",
        skip_serializing_if = "Option::is_none"
    )]
    pub activity_description: Option<String>,
    /// The key of the activity described in the history record.
    #[serde(
        rename = "activityDescriptionKey",
        skip_serializing_if = "Option::is_none"
    )]
    pub activity_description_key: Option<String>,
    /// The description of the email address associated the history record.
    #[serde(rename = "emailDescription", skip_serializing_if = "Option::is_none")]
    pub email_description: Option<String>,
    /// The description key of the email address associated the history record.
    #[serde(
        rename = "emailDescriptionKey",
        skip_serializing_if = "Option::is_none"
    )]
    pub email_description_key: Option<String>,
    #[serde(rename = "actor", skip_serializing_if = "Option::is_none")]
    pub actor: Option<Box<crate::models::HistoryMetadataActor>>,
    #[serde(rename = "generator", skip_serializing_if = "Option::is_none")]
    pub generator: Option<Box<crate::models::HistoryMetadataGenerator>>,
    #[serde(rename = "cause", skip_serializing_if = "Option::is_none")]
    pub cause: Option<Box<crate::models::HistoryMetadataCause>>,
    /// Additional arbitrary information about the history record.
    #[serde(rename = "extraData", skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<::std::collections::HashMap<String, String>>,
}

impl IssueUpdateDetailsHistoryMetadata {
    /// Additional issue history details.
    pub fn new() -> IssueUpdateDetailsHistoryMetadata {
        IssueUpdateDetailsHistoryMetadata {
            r#type: None,
            description: None,
            description_key: None,
            activity_description: None,
            activity_description_key: None,
            email_description: None,
            email_description_key: None,
            actor: None,
            generator: None,
            cause: None,
            extra_data: None,
        }
    }
}
