/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// IssueSecurityLevelMember : Issue security level member.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IssueSecurityLevelMember {
    /// The ID of the issue security level member.
    #[serde(rename = "id")]
    pub id: i64,
    /// The ID of the issue security level.
    #[serde(rename = "issueSecurityLevelId")]
    pub issue_security_level_id: i64,
    #[serde(rename = "holder")]
    pub holder: Box<crate::models::IssueSecurityLevelMemberHolder>,
}

impl IssueSecurityLevelMember {
    /// Issue security level member.
    pub fn new(
        id: i64,
        issue_security_level_id: i64,
        holder: crate::models::IssueSecurityLevelMemberHolder,
    ) -> IssueSecurityLevelMember {
        IssueSecurityLevelMember {
            id,
            issue_security_level_id,
            holder: Box::new(holder),
        }
    }
}
