/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JiraExpressionsComplexityBean {
    #[serde(rename = "steps")]
    pub steps: Box<crate::models::JiraExpressionsComplexityBeanSteps>,
    #[serde(rename = "expensiveOperations")]
    pub expensive_operations: Box<crate::models::JiraExpressionsComplexityBeanExpensiveOperations>,
    #[serde(rename = "beans")]
    pub beans: Box<crate::models::JiraExpressionsComplexityBeanBeans>,
    #[serde(rename = "primitiveValues")]
    pub primitive_values: Box<crate::models::JiraExpressionsComplexityBeanPrimitiveValues>,
}

impl JiraExpressionsComplexityBean {
    pub fn new(
        steps: crate::models::JiraExpressionsComplexityBeanSteps,
        expensive_operations: crate::models::JiraExpressionsComplexityBeanExpensiveOperations,
        beans: crate::models::JiraExpressionsComplexityBeanBeans,
        primitive_values: crate::models::JiraExpressionsComplexityBeanPrimitiveValues,
    ) -> JiraExpressionsComplexityBean {
        JiraExpressionsComplexityBean {
            steps: Box::new(steps),
            expensive_operations: Box::new(expensive_operations),
            beans: Box::new(beans),
            primitive_values: Box::new(primitive_values),
        }
    }
}
