/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// JiraExpressionsComplexityBeanBeans : The number of Jira REST API beans returned in the response.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JiraExpressionsComplexityBeanBeans {
    /// The complexity value of the current expression.
    #[serde(rename = "value")]
    pub value: i32,
    /// The maximum allowed complexity. The evaluation will fail if this value is exceeded.
    #[serde(rename = "limit")]
    pub limit: i32,
}

impl JiraExpressionsComplexityBeanBeans {
    /// The number of Jira REST API beans returned in the response.
    pub fn new(value: i32, limit: i32) -> JiraExpressionsComplexityBeanBeans {
        JiraExpressionsComplexityBeanBeans { value, limit }
    }
}
