/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// LinkedIssueFields : The fields associated with the issue.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LinkedIssueFields {
    /// The summary description of the linked issue.
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Box<crate::models::FieldsStatus>>,
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<Box<crate::models::FieldsPriority>>,
    #[serde(rename = "assignee", skip_serializing_if = "Option::is_none")]
    pub assignee: Option<Box<crate::models::FieldsAssignee>>,
    #[serde(rename = "timetracking", skip_serializing_if = "Option::is_none")]
    pub timetracking: Option<Box<crate::models::FieldsTimetracking>>,
    #[serde(rename = "issuetype", skip_serializing_if = "Option::is_none")]
    pub issuetype: Option<Box<crate::models::IssueTypeDetails>>,
    #[serde(rename = "issueType", skip_serializing_if = "Option::is_none")]
    pub issue_type: Option<Box<crate::models::FieldsIssueType>>,
}

impl LinkedIssueFields {
    /// The fields associated with the issue.
    pub fn new() -> LinkedIssueFields {
        LinkedIssueFields {
            summary: None,
            status: None,
            priority: None,
            assignee: None,
            timetracking: None,
            issuetype: None,
            issue_type: None,
        }
    }
}
