/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// ProjectLandingPageInfo : The project landing page info.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProjectLandingPageInfo {
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "projectKey", skip_serializing_if = "Option::is_none")]
    pub project_key: Option<String>,
    #[serde(rename = "projectType", skip_serializing_if = "Option::is_none")]
    pub project_type: Option<String>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "simplified", skip_serializing_if = "Option::is_none")]
    pub simplified: Option<bool>,
    #[serde(rename = "boardId", skip_serializing_if = "Option::is_none")]
    pub board_id: Option<i64>,
    #[serde(rename = "boardName", skip_serializing_if = "Option::is_none")]
    pub board_name: Option<String>,
    #[serde(rename = "simpleBoard", skip_serializing_if = "Option::is_none")]
    pub simple_board: Option<bool>,
    #[serde(rename = "queueId", skip_serializing_if = "Option::is_none")]
    pub queue_id: Option<i64>,
    #[serde(rename = "queueName", skip_serializing_if = "Option::is_none")]
    pub queue_name: Option<String>,
    #[serde(rename = "queueCategory", skip_serializing_if = "Option::is_none")]
    pub queue_category: Option<String>,
}

impl ProjectLandingPageInfo {
    /// The project landing page info.
    pub fn new() -> ProjectLandingPageInfo {
        ProjectLandingPageInfo {
            url: None,
            project_key: None,
            project_type: None,
            attributes: None,
            simplified: None,
            board_id: None,
            board_name: None,
            simple_board: None,
            queue_id: None,
            queue_name: None,
            queue_category: None,
        }
    }
}
