/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// StatusCreateRequest : Details of the statuses being created and their scope.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StatusCreateRequest {
    /// Details of the statuses being created.
    #[serde(rename = "statuses")]
    pub statuses: Vec<crate::models::StatusCreate>,
    #[serde(rename = "scope")]
    pub scope: Box<crate::models::StatusScope>,
}

impl StatusCreateRequest {
    /// Details of the statuses being created and their scope.
    pub fn new(
        statuses: Vec<crate::models::StatusCreate>,
        scope: crate::models::StatusScope,
    ) -> StatusCreateRequest {
        StatusCreateRequest {
            statuses,
            scope: Box::new(scope),
        }
    }
}
